config/routes.rb
Rails.application.routes.draw do
  resources :todo_lists
  resources :todo_items
  get 'bonjour/index'
  root 'bonjour#index'


  namespace 'api' do
    namespace 'v1' do
      get 'info/index' => 'info#index'
      patch 'todo_items/update/:id/:position' => 'todo_items#update'
      get 'todo_items/index/:id/:position' => 'todo_items#index'
    end
  end

  get '/*path', to: 'bonjour#index', format: false
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo_item.rb
class TodoItem < ApplicationRecord
  belongs_to :todo_list
  acts_as_list scope: :todo_list
  
end

app/models/todo_list.rb
class TodoList < ApplicationRecord
  has_many :todo_items, -> { order(position: :asc) }

  acts_as_list
end

app/controllers/api/v1/info_controller.rb
module Api
  module V1
    class InfoController < ApplicationController
      def index
        render :json => "{msg:'hello world'}"
      end
    end
  end
end

app/controllers/api/v1/todo_items_controller.rb
module Api
  module V1
    class TodoItemsController < ApplicationController
      #skip_before_action :verify_authenticity_token
      def index
        @todo_item = TodoItem.find(params[:id])
        newPosition = params[:position].to_i
        render :json => "{newPosition: #{newPosition}, todo: #{@todo_item.to_json}}"
      end
      def update
        @todo_item = TodoItem.find(params[:id])
        newPosition = params[:position].to_i
        puts "{newPosition: #{newPosition}, todo: #{@todo_item.to_json}}"
        #@todo_item.remove_from_list
        @todo_item.set_list_position(newPosition)
        @todo_item.save()
        render :json => @todo_item.to_json
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/bonjour_controller.rb
class BonjourController < ApplicationController
  def index
  end
end

app/controllers/todo_items_controller.rb
class TodoItemsController < ApplicationController
  before_action :set_todo_item, only: [:show, :edit, :update, :destroy]

  # GET /todo_items
  # GET /todo_items.json
  def index
    @todo_items = TodoItem.all.order(:position)
  end

  # GET /todo_items/1
  # GET /todo_items/1.json
  def show
  end

  # GET /todo_items/new
  def new
    @todo_item = TodoItem.new
  end

  # GET /todo_items/1/edit
  def edit
  end

  # POST /todo_items
  # POST /todo_items.json
  def create
    @todo_item = TodoItem.new(todo_item_params)

    respond_to do |format|
      if @todo_item.save
        format.html { redirect_to @todo_item, notice: 'Todo item was successfully created.' }
        format.json { render :show, status: :created, location: @todo_item }
      else
        format.html { render :new }
        format.json { render json: @todo_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todo_items/1
  # PATCH/PUT /todo_items/1.json
  def update
    respond_to do |format|
      if @todo_item.update(todo_item_params)
        format.html { redirect_to @todo_item, notice: 'Todo item was successfully updated.' }
        format.json { render :show, status: :ok, location: @todo_item }
      else
        format.html { render :edit }
        format.json { render json: @todo_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todo_items/1
  # DELETE /todo_items/1.json
  def destroy
    @todo_item.destroy
    respond_to do |format|
      format.html { redirect_to todo_items_url, notice: 'Todo item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo_item
      @todo_item = TodoItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def todo_item_params
      params.require(:todo_item).permit(:name, :position, :todo_list_id)
    end
end

app/controllers/todo_lists_controller.rb
class TodoListsController < ApplicationController
  before_action :set_todo_list, only: [:show, :edit, :update, :destroy]

  # GET /todo_lists
  # GET /todo_lists.json
  def index
    @todo_lists = TodoList.all.order(:position)
  end

  # GET /todo_lists/1
  # GET /todo_lists/1.json
  def show
  end

  # GET /todo_lists/new
  def new
    @todo_list = TodoList.new
  end

  # GET /todo_lists/1/edit
  def edit
  end

  # POST /todo_lists
  # POST /todo_lists.json
  def create
    @todo_list = TodoList.new(todo_list_params)

    respond_to do |format|
      if @todo_list.save
        format.html { redirect_to @todo_list, notice: 'Todo list was successfully created.' }
        format.json { render :show, status: :created, location: @todo_list }
      else
        format.html { render :new }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todo_lists/1
  # PATCH/PUT /todo_lists/1.json
  def update
    respond_to do |format|
      if @todo_list.update(todo_list_params)
        format.html { redirect_to @todo_list, notice: 'Todo list was successfully updated.' }
        format.json { render :show, status: :ok, location: @todo_list }
      else
        format.html { render :edit }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todo_lists/1
  # DELETE /todo_lists/1.json
  def destroy
    @todo_list.destroy
    respond_to do |format|
      format.html { redirect_to todo_lists_url, notice: 'Todo list was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo_list
      @todo_list = TodoList.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def todo_list_params
      params.require(:todo_list).permit(:name, :references)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bonjour_helper.rb
module BonjourHelper
end

app/helpers/todo_items_helper.rb
module TodoItemsHelper
end

app/helpers/todo_lists_helper.rb
module TodoListsHelper
end

app/views/bonjour/index.html.haml
#webpack_entry_point 
  %app

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestVue</title>
    <%= csrf_meta_tags %>
    <meta name="google-site-verification" content="WIn-UGdx6vbsmrx7vhyqJVttikYkUh4tKKzq8pVTKZo" />

    <script src="https://www.gstatic.com/firebasejs/4.10.1/firebase.js"></script>
        
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'hello_vue' %>
    <%= stylesheet_pack_tag 'hello_vue' %>
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.3.1/dist/leaflet.css"
      integrity="sha512-Rksm5RenBEKSKFjgI3a41vrjkw4EVPlJ3+OiI65vTjIdo9brlAacEuKOiQ5OFh7cOI1bkDwLqdLw3Zg0cRJAAQ=="
      crossorigin=""/>

    <script defer src="https://use.fontawesome.com/releases/v5.0.6/js/all.js"></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/todo_items/_form.html.haml
= form_for @todo_item do |f|
  - if @todo_item.errors.any?
    #error_explanation
      %h2= "#{pluralize(@todo_item.errors.count, "error")} prohibited this todo_item from being saved:"
      %ul
        - @todo_item.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :position
    = f.number_field :position
  .actions
    = f.submit 'Save'

app/views/todo_items/edit.html.haml
%h1 Editing todo_item

= render 'form'

= link_to 'Show', @todo_item
\|
= link_to 'Back', todo_items_path

app/views/todo_items/index.html.haml
%h1 Listing todo_items

%table
  %thead
    %tr
      %th Name
      %th Position
      %th
      %th
      %th

  %tbody
    - @todo_items.each do |todo_item|
      %tr
        %td= todo_item.name
        %td= todo_item.position
        %td= link_to 'Show', todo_item
        %td= link_to 'Edit', edit_todo_item_path(todo_item)
        %td= link_to 'Destroy', todo_item, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Todo item', new_todo_item_path

app/views/todo_items/new.html.haml
%h1 New todo_item

= render 'form'

= link_to 'Back', todo_items_path

app/views/todo_items/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @todo_item.name
%p
  %b Position:
  = @todo_item.position

= link_to 'Edit', edit_todo_item_path(@todo_item)
\|
= link_to 'Back', todo_items_path

app/views/todo_lists/_form.html.haml
= form_for @todo_list do |f|
  - if @todo_list.errors.any?
    #error_explanation
      %h2= "#{pluralize(@todo_list.errors.count, "error")} prohibited this todo_list from being saved:"
      %ul
        - @todo_list.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :name
    = f.text_field :name
  .actions
    = f.submit 'Save'

app/views/todo_lists/edit.html.haml
%h1 Editing todo_list

= render 'form'

= link_to 'Show', @todo_list
\|
= link_to 'Back', todo_lists_path

app/views/todo_lists/index.html.haml
%h1 Listing todo_lists

%table
  %thead
    %tr
      %th Name
      %th
      %th
      %th

  %tbody
    - @todo_lists.each do |todo_list|
      %tr
        %td= todo_list.name
        %td= link_to 'Show', todo_list
        %td= link_to 'Edit', edit_todo_list_path(todo_list)
        %td= link_to 'Destroy', todo_list, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Todo list', new_todo_list_path

app/views/todo_lists/new.html.haml
%h1 New todo_list

= render 'form'

= link_to 'Back', todo_lists_path

app/views/todo_lists/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @todo_list.name


= link_to 'Edit', edit_todo_list_path(@todo_list)
\|
= link_to 'Back', todo_lists_path